### ISSUE TITLE
usage improvement

### ISSUE THREAD

**Issue by magiceye** [miloyip/rapidjson#229]
1. consistent with c++ operator[], if there is not a key in doc, [] should insert a default Value object and return its reference.
2. before use a doc must call doc.Parse("{}"); This is meaningless if doc not parse from file
3. API should support std::string. It seems there is no conversion from std::string to GenericValue<Encoding>, I don't know the reason, but it really incovenient. 
4. copy or not copy control by pass Allocator. This is weird because it let user think: "Can I pass a Allocator object which doesn't belong to this doc?" Why not let user pass string_ref or string to control ref or copy.
5. support shorter add element API. For example, add a string field into doc:
std::string v("value");
rapidjson::Value value;
value.SetString(v.c_str(), v.length());
doc.AddMember("v", value, json.GetAllocator());
it is too much typing. Why not doc["v"].SetString(v);? even doc["v"] = v;

**Comment by miloyip** [comment]
1. Not possible in `Value` because this will need an allocator as parameter (see 4 too). Also, this is not preferable for performance. You can add helper function for this.
2. By default it is a null value. You can simply use `doc.SetObject()`, `doc.SetArray()` or other types (for new JSON spec).
3. Please check [RAPIDJSON_HAS_STDSTRING](http://miloyip.github.io/rapidjson/group___r_a_p_i_d_j_s_o_n___c_o_n_f_i_g.html#ga2f2eef0ee4477f3fe5874703a66e997f).
4. Yes. This API design is a bit weird but it saves 4 or 8 bytes for each `Value` to save an allocator. This saving is come at the cost of coding convenience.
5. You may use `Move()` to prevent creating a temp variable for value. `doc.AddMember("v", Value(v, a).Move(), a)`. Passing allocator has the limitation as mentioned in 1 and 4.

We may consider adding another simpler DOM implementation later for those who don't need maximal performance, and just using `vector` and `map`/`unordered_map`, polymorphism and supporting copy-semantics. Comments are welcome.

**Comment by magiceye** [comment]
So the conception of Allocator influence whole design much. Personally I feel 99.9% user will not define  their own Allocator and nowadays system malloc performance is good enough to beat special ones like boost.Pool. In practical view, the overhead is a bit heavy. 
Current version of rapidjson is good at parse from file, it's indeed fast. But for construct json object which used in network data transmission, it's not so convenient.

**Comment by miloyip** [comment]
JSON Pointer should help a lot of problem for constructing and modifying values.
I close this now.
