### ISSUE TITLE
Invalid UTF-8 characters 0xC0 and 0xC1 seem to be allowed

### ISSUE THREAD

**Issue by AnAkkk** [miloyip/rapidjson#325]
According to http://tools.ietf.org/html/rfc3629

> The octet values C0, C1, F5 to FF never appear

Rapidjson doesn't seem to check against these values in the Writer::WriteString function, I had a json with 0xC1.

**Comment by miloyip** [comment]
Yes. RapidJSON does not validate the encodings of string in `Writer` if the source and target encodings are the same (in this case I think both are UTF8). If the encodings are not the same, the transcoding would able to validate invalid codepoint in the source string.

Currently, RapidJSON only optionally support validation of string encodings during parsing.

Do you think validation of source string also needed? I think it can be implemented by simply wrapping the existing `Writer` and `PrettyWriter`, so it validates the encoding of the string in `WriteString()` before calling the real one. If you think it is needed, I can consider putting it in the next version.

**Comment by AnAkIn1** [comment]
Well, the problem is that I had to send some data as a string to a web server which contained invalid UTF-8 characters and the web server json lib was rejecting the data every time. 
After a few hours of search, I actually found out that I shouldn't send that kind of data as a json string in the first place, I didn't know that such characters were disallowed.
Yes, I think it might be good to check for the validity of the source string, and apparently some other libraries like jansson does it :)

**Comment by miloyip** [comment]
At the mean time, you can use UTF8 as source and ASCII as target encoding, so it will validate the source encoding. As ASCII is subset of UTF8, an ASCII JSON is also an UTF8 JSON. The server should able to process those JSONs.

**Comment by AnAkkk** [comment]
This doesn't seem to be working properly. 
If I set kWriteValidateEncodingFlag on my Writer and I call GetString() on my StringBuffer, the json is cut at the exact place where there was the invalid UTF-8 character.
If I don't set kWriteValidateEncodingFlag, then the json is not cut, but the json is invalid.

**Comment by miloyip** [comment]
Have you checked the return value of `doc.Accept(writer)`? I assume it will return `false` when validation fail.

**Comment by AnAkkk** [comment]
Indeed, it does return false. I expected the bad characters to be escaped with \u though, shouldn't that be the case? Isn't there a way to do that?

**Comment by miloyip** [comment]
It can only validates  the UTF-8 strings, but not able to correct it.

> I expected the bad characters to be escaped with \u though, shouldn't that be the case? Isn't there a way to do that?
The `ASCII<>` thing I proposed is also a way to do validation. To output `\u` escapes, the source must be a correct UTF sequence which can be decoded into Unicode code points.

**Comment by AnAkkk** [comment]
> To output \u escapes, the source must be a correct UTF sequence which can be decoded into Unicode code points.

Is that part of the standard, or specific to the library?

**Comment by miloyip** [comment]
In [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf):
> Any code point may be represented as a hexadecimal number. The meaning of such a number is determined by ISO/IEC 10646. If the code point is in the Basic Multilingual Plane (U+0000 through U+FFFF), then it may be represented as a six-character sequence: a reverse solidus, followed by the lowercase letter u, followed by four hexadecimal digits that encode the code point. Hexadecimal digits can be digits (U+0030 through U+0039) or the hexadecimal letters A through F in uppercase (U+0041 through U+0046) or lowercase (U+0061 through U+0066). So, for example, a string containing only a single reverse solidus character may be represented as "\u005C".
...
To escape a code point that is not in the Basic Multilingual Plane, the character is represented as a twelve character sequence, encoding the UTF-16 surrogate pair. So for example, a string containing only the G clef character (U+1D11E) may be represented as "\uD834\uDD1E". 

So that `\u` are actually UTF-16 code units. To convert UTF-8 sequence into UTF-16, it must be decoded as code points, and then encoded as UTF-16.

This is not specific to the library.
