### ISSUE TITLE
No GetFloat?

### ISSUE THREAD

**Issue by Phyks** [miloyip/rapidjson#341]
Hi,

There are several ways to retrieve an int from a rapidjson::Value, either 32 or 64 bits. But there is only one method to retrieve a floating point value, which is GetDouble.

There is no GetFloat, to retrieve a 32 bits floating value.

Is it done on purpose? What about adding such a method?

Context: I compile with `-Wnarrowing` as I should not do any implicit narrowing conversion, which might lose precision in the code I am working on (imposed coding guideline) and writing static_cast every time is a pain for readability.

**Comment by miloyip** [comment]
It is done on purpose. Or in other words, it is designed as so.
Since JSON specification does not have a strict rule on this, but in http://www.ietf.org/rfc/rfc7159.txt mentioned:

> This specification allows implementations to set limits on the range
   and precision of numbers accepted.  Since software that implements
   IEEE 754-2008 binary64 (double precision) numbers [IEEE754] is
   generally available and widely used, good interoperability can be
   achieved by implementations that expect no more precision or range
   than these provide, in the sense that implementations will
   approximate JSON numbers within the expected precision.

Using double precision floating point number for storing the converted value seems a suitable choice.

Regarding to your context, As the SAX or DOM API uses double precision floating point representation for decimal numbers, there must be narrowing conversion if that is needed. The problem is, whether this lossy conversion is done in the API, or in the user code.

I personally prefer to make the lossy conversion explicitly. But if you think it will be better to provide `GetFloat()` and `SetFloat()`, I think a compromise is to provide them but as a conditional compilation option, like `RAPIDJSON_USE_LOSSYFLOAT`.

Internally, I don't quite want to redo a separate pipeline for storing and processing `float`. But this is all open for discuss.

**Comment by Phyks** [comment]
Hmm, indeed I was not thinking at all in a different pipeline to store and process `float`.

I think that providing a `GetFloat()` and `SetFloat()` handler which would handle the explicit conversion itself might be useful.

**Comment by pah** [comment]
I think, it might be possible to detect floating-point values that can be losslessly converted to a 32-bit `float` value (and thus providing `IsFloat`/`GetFloat`/`SetFloat` similarly to the handling of 32-bit integral values). Didn't check, how difficult it would be, to add it to the current parsing logic, though.

**Comment by miloyip** [comment]
It is not difficult, just checking if the mantissa lower bits are all zero and exponent is within range.
However, currently it is not permitted to `GetInt()` of a value if the actual type is `double` or `int64_t`.
Only `integer` to `double` is converted automatically with potential precision loss.

**Comment by pavi32** [comment]
Then how to put float value and get that float value without loss of any precision values

**Comment by miloyip** [comment]
All  `float` values are convertible to `double` without loss of precision:

~~~cpp
float f = ...;
double d = f; // no compiler warning because it is safe.
float f2 = static_cast<float>(d);
assert(f == f2);
~~~

**Comment by Phyks** [comment]
Awesome! Thanks!
