### ISSUE TITLE
AddMember should return the newly created member

### ISSUE THREAD

**Issue by Bu11etmagnet** [miloyip/rapidjson#348]
Currently, AddMember returns the containing (outer) object. This is information we already have. What we don't have is a reference to the newly created member, so we have to do a (linear) search or something silly-looking like this:

```cpp
    // add an empty array member
    value.SetObject().AddMember("SS", rapidjson::Value{rapidjson::kArrayType}, value.GetAllocator());
    // push back a string into the last member
    (--value.MemberEnd())->value.PushBack("s", value.GetAllocator());
```
which results in the expected {"SS":["s"]}

Unfortunately, changing AddMember like this would break the API, but maybe a new method, e.g. AddMemberAndReturnIt, could be added.

**Comment by miloyip** [comment]
You can do the `PushBack` first and do `AddMember` at last. Since move semantics is enforced, it won't have performance overhead of deep cloning when doing the `AddMember`.

~~~cpp
auto& a = document.GetAllocator();
value.setObject().AddMember("SS", Value(kArrayType).PushBack("s", a), a);
~~~

**Comment by fdwr** [comment]
This was so confusing of a surprise for me that rapidjson just returns the very same object that I already have, rather than the new child that I want to modify further. Having a Back() method or having AddMember returned the new node would be much more valuable in all my uses, as constructing a child tree first and then linking it to the parent is unnatural for my program. I worked around it by adding an AddMember helper which returns the new node.

**Comment by miloyip** [comment]
Sorry for the confusion. May consider other alternatives in the future. But to keep the API consistent it will not be changed in this major version.

**Comment by tsingakbar** [comment]
从编码本身讲，先构造好再AddMember，不光是违反直觉，我觉得还会引入更高的圈复杂度，特别是我要添加的object里面层次也多的情况下。
大佬的设计是std::string.append式的，可以串起来调用，但是我觉得json的AddMember场景就是针对json object的，这个场景c++开发人员更熟悉的类似场景是std::map.insert，可以返回新插入元素的iterator。
希望新版rapidjson能出个返回新插入元素版本的AddMemberXXX。现在的代码里我是宁肯插入之后多find一次，都不想在最后AddMember……
