### ISSUE TITLE
Bug in tutorial.cpp

### ISSUE THREAD

**Issue by MelosGmbhRadicke** [miloyip/rapidjson#354]
Hi,

I think there is a bug in "tutorial.cpp"

    char buffer[sizeof(json)];
    memcpy(buffer, json, sizeof(json));

properly is:

    char buffer[strlen(jsonBill.c_str()) + 1];
    buffer[strlen(jsonBill.c_str())] = '\0';
    memcpy(buffer, jsonBill.c_str(), strlen(jsonBill.c_str()) );
	
...can this be?

CU

Olaf

**Comment by miloyip** [comment]
It's not a bug. `json` in that example is in type `char [n]` where `n` is the constant number of characters (that I haven't counted it here). `sizeof(json)` equals to that `n`, and it is determined in compile-time. But if `json` is a `char*` instead, then you need to determine the length of it by other ways. `strlen()` is a way but it cannot handle a JSON with `\u0000` character (which is legal).

`strlen()` is a runtime function. Your suggested code cannot be compiled for C++, since C++ does not support [VLA](http://en.wikipedia.org/wiki/Variable-length_array). A possible solution for `char* json` is:

~~~cpp
size_t size = strlen(json) + 1;
char* buffer = (char*)malloc(size);
memcpy(buffer, json, size);
// ...
free(buffer);
~~~

These lines also do exactly the same:
~~~cpp
char* buffer = (char*)strdup(json);
// ...
free(buffer);
~~~

Since in your code `jsonBill` look likes a `std::string`, You can use `size_t size = jsonBill.size();` and the others are the same.

**Comment by MelosGmbhRadicke** [comment]
Thank you for you quick answer. And another question: Why can't I use std::string directly?

Best regards

Olaf

**Comment by miloyip** [comment]
For *insitu* parsing, the parser will write into the buffer. `string::c_str()` returns `const char*`, which cannot be written.

For normal parsing, we are considering to support directly parsing a `std::string` in the API, but basically it is just simply doing `str.c_str()`.
