### ISSUE TITLE
How to insert document as node into another DOM tree?

### ISSUE THREAD

**Issue by mloskot** [miloyip/rapidjson#366]
Let's take two `Document` objects created by parsing the following .json files:
* person.json
```
{ "person": { "name": { "first": "Adam", "last": "Thomas" } } }
```
* address.json
```
{ "address": { "city": "Moscow", "street": "Quiet" } }
```
What is the best way to insert the whole "address" node into the "person" DOM tree as a sibling node of the "name"?

So, the final document it reads
```
{
  "person": {
    "name": { "first": "Adam", "last": "Thomas" },
    "address": { "city": "Moscow", "street": "Quiet" }
  }
}
```

Here is code that creates instances of the two DOM trees:
```
Document person;
person.Parse("{\"person\":{\"name\":{\"first\":\"Adam\",\"last\":\"Thomas\"}}}");
RAPIDJSON_ASSERT(!person.HasParseError());

Document address;
address.Parse("{\"address\":{\"city\":\"Moscow\",\"street\":\"Quiet\"}}");
RAPIDJSON_ASSERT(!address.HasParseError());
```
followed by two possible solutions I was able to come up with:

1. Requires to know name of the node in the source DOM - inconvenient, impractical:
    ```
    person["person"].AddMember("address", address["address"], person.GetAllocator());
    ```

2. Requires use of iterators - not bad, but don't *feel* like suitable tool in this context:
    ```
    auto srcRoot = address.MemberBegin();
    person["person"].AddMember(srcRoot->name, srcRoot->value, person.GetAllocator());
```

Is there another, better way to achieve the same?

**Comment by miloyip** [comment]
The example code may have problem that two `Document`s have their own allocators. So you must ensure the two `Document` co-exist when using them, otherwise dangling pointer may happen.

I think your first solution is better, because it states that the address document contains the `address` key explicitly. I don't know if there may be other keys in future in the JSON and the order of keys should not be sensitive, therefore the 2nd solution may cause problem.

To prevent the life-cycle issue, you can deep-clone the value in `address` document:

~~~cpp
Value addressValue = Value(addres["address"], person.GetAllocator());
person["person"].AddMember("address", addressValue, person.GetAllocator());
~~~

Or, to prevent the deep-cloning, you can use the same allocator for both `Document`s:

~~~cpp
Documnet address(person.GetAllocator());
// ...
~~~

**Comment by mloskot** [comment]
@miloyip Thanks for the explanation and pointing at the possible issues, very informative.

**Comment by bferg88** [comment]
Note that the recommendation above to use the same allocator in the second document has a small typo. You must pass the allocator as a pointer:
```c++
Document address(&person.GetAllocator());
```
