### ISSUE TITLE
How to correctly pass Document as Value?

### ISSUE THREAD

**Issue by mloskot** [miloyip/rapidjson#380]
Let's take a function declared as `void foo(Value const& v);`

Technically, due to public inheritance from `Value` (the C++ *Explicit type conversion* rules), it is possible to pass `Document` object by reference to `Value`:
```
Document d;
d.Parse(L"{\"person\":{\"name\":{\"first\":\"Adam\",\"last\":\"Thomas\"}}}");
foo(d);
```
Is it kosher and canonical way by design?
Any caveats to be aware of?

Wouldn't the `Document` interface become more self-descriptive if there was `Value const& Document::Root()` method available?

**Comment by miloyip** [comment]
Passing const pointer or reference of `Document` as `Value` should be safe. As the design of `Document` and `Value` should have not violated [Liskov substitution principle (LSP)](https://en.wikipedia.org/wiki/Liskov_substitution_principle).

I have also considered of just letting `Document` aggregate a `Value` as root instead of inheritance. However, that will complicate the accessing API, such as `d["person"]` needs to become `q.Root()["person"]`. Or a bunch of delegation functions are added to `Document`. So I have chose to use public inheritance finally.

A common problem for inheritance is [object slicing](https://en.wikipedia.org/wiki/Object_slicing). But as `Value` uses move semantics, object slicing cannot occur.

I can think of a problem when `Value` is passed as non-const pointer/reference, and the function needs to get a suitable allocator. It may be needed to pass the allocator explicitly.

**Comment by mloskot** [comment]
The LSP vs object slicing is the important confirmation. Thanks.

If you think it would be good to add this Q&A to the FAQ, let me know and I'll prepare a PR.
