### ISSUE TITLE
Parsing string with a space error

### ISSUE THREAD

**Issue by apamment** [miloyip/rapidjson#408]
I'm getting a parse error from JSON created with QT's json functions. 

This is the full JSON attached, the error is on line 229 with the space between "Platformer" and "Pack" if I remove it the JSON parses fine. Strangely there are other string values with spaces that are parsed just fine.

http://pastebin.com/taNqBYBv

**Comment by miloyip** [comment]
I used some JSON lint tools online ([e.g.](http://www.freeformatter.com/json-validator.html)) and found that in line 241:

~~~
"levelbackgrounddata": "-1,-1,-1...-
1..."
~~~

There is a carriage return character between the quotes, which is illegal. If this is just because of some problem when you post the JSON, please tell me if the RapidJSON parser returns an error code.

**Comment by apamment** [comment]
That's actually one massive long line in my json file and parses fine, i guess pastebin has a limit on line lengths and has chopped it up.

The error it reports is : The document root must not follow by other values.

**Comment by miloyip** [comment]
This error means there are non-whitespace characters after the root value (normally `}` or `]`), before the null character.

I think it may be the case that, you have read passing the end of the file, e.g. including EOF.

It is also possible to let the parser terminate the parsing process after the root value is parsed, by using `kParseStopWhenDoneFlag`.

**Comment by apamment** [comment]
That fixed it. Thankyou.
