### ISSUE TITLE
Simplify parsing by adding a FindValue function

### ISSUE THREAD

**Issue by Llerd** [miloyip/rapidjson#410]
Hi,

Due to performance issues, I'm currently looking into replacing my use of the jsoncpp library with rapidjson. It looks great so far, but one issue I have is that robust parsing seems a bit too cumbersome.

I can use iterators to use a single lookup to a value to do this:

	Value::ConstMemberIterator myList = object.FindMember("mylist");
	if (myList == object.MemberEnd() || !myList->value.IsArray())
		return false;

	uint nList = myList->value.Size();
	for (uint i = 0; i < nList; i++)
	{
		const Value &val = myList->value[i];
		// process val
	}
	
However, would be possible to add a FindValue function working like this?

		const Value &myList = object.FindValue("mylist");
		if (!myList.IsArray())
			return false;

		uint nList = myList.Size();
		for (uint i = 0; i < nList; i++)
		{
			const Value &val = myList[i];
			// process val
		}

Which would make it a bit cleaner. If the member does not exist, FindValue would return a static item of type kNullType. However, I understand that this might be problematic with rapidjsons header only approach.

**Comment by miloyip** [comment]
This is not possible because the returned type is a reference. If the required value is not found, it can not return a new `Value` object. 

Actually in very early version of RapidJSON, it does something like this by returning a Meyer singleton of null value. However, this does not work for non-const access, as the returned value can be modified.

[A new set of API for JSON Pointer](http://rapidjson.org/md_doc_pointer.html) is now in master branch. It can do something like:

~~~cpp
if (const Value* myList = GetValueByPointer(object, "/mylist")) {
    if (!myList->IsArray())
        return;
    // ...
}
~~~

JSON pointer is easier, cleaner (but slower) to access a value within multiple levels in a hierarchy.

**Comment by Llerd** [comment]
Thanks for the response! Since performance is key for what I need, the pointer interface is not right.

>If the required value is not found, it can not return a new Value object.

I it could still return a static item of type kNullType, right? Jsoncpp actually handles it like that.

An option that would solve this is to return a const Value * (like the Pointer API), which would remove the need for the static null item. A second, maybe better, option would be to supply a default item in the function that would be returned if not found, something like:

```
const Value &FindValue(const Value &value, const Value &name, const Value &default) const
{
	Value::ConstMemberIterator member = _value.MemberBegin();
	for (; member != _value.MemberEnd(); ++member)
		if (name.StringEqual(member->name))
			return member->value;

	return default;
}
```

Either way, it's an easy local change for me. I just wanted to suggested it as I think it would be useful for other people as well. Great work on the library!

**Comment by miloyip** [comment]
> it could still return a static item of type kNullType, right? Jsoncpp actually handles it like that.
As I said, it was done before and find out that design is prone to problem.

There is a `GetValueByPointerWithDefault()` which does the default value thing and returns a reference instead of pointer.

Some people has raised similar discussion in some issues before (I could not dig it out now), and it is actually easy to have your own helper functions (if you do not want to modify the headers of RapidJSON), similar to JSON Pointer API.

**Comment by Llerd** [comment]
>As I said, it was done before and people found out that that design is prone to problem.

Ah, sorry, I misunderstood you saying that. I had no clue it was called a Meyer singleton. :) That would have been my preferred way of accessing things, including operator\[\](const char*), and where non-const access would require a more specific call. I understand the arguments against it though.

>it is actually easy to have your own helper functions

Yeah, that's my current approach.

Thanks again!
