### ISSUE TITLE
MSVC 2008 issue

### ISSUE THREAD

**Issue by hellmersjl3ds** [miloyip/rapidjson#413]
Please don't judge me for being on an old compiler.

The error

D:\xfer_D\rapidjson\build>cmake ..
-- Building for: Visual Studio 9 2008
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:4 (PROJECT):
  No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!
See also "D:/xfer_D/rapidjson/build/CMakeFiles/CMakeOutput.log".
See also "D:/xfer_D/rapidjson/build/CMakeFiles/CMakeError.log".

Anyway I can get the build to work for MSVC 2008?

**Comment by miloyip** [comment]
Sorry I don't have this environment to try it out.

However, since RapidJSON is header-only library, the cmake process is only for building the unit tests, performance tests, and examples. 

You may try to use RapidJSON in your own project and see if there is compilation problems.

**Comment by aj664** [comment]
MSVC2008 compile error..   the code is the Usage example on the front page of your github page...

1>Compiling...
1>rapidjson_tests.cpp
1>c:\program files (x86)\msvc9\vc\include\rapidjson\internal/strtod.h(156) : error C2220: warning treated as error - no 'object' file generated
1>c:\program files (x86)\msvc9\vc\include\rapidjson\internal/strtod.h(156) : warning C4640: 'kPow10' : construction of local static object is not thread-safe
1>C:\Program Files (x86)\MSVC9\VC\include\rapidjson/document.h(2290) : warning C4347: behavior change: 'rapidjson::GenericDocument<Encoding> &rapidjson::GenericDocument<Encoding>::Parse<0>(const char *)' is called instead of 'rapidjson::GenericDocument<Encoding> &rapidjson::GenericDocument<Encoding>::Parse(const char *)'
1>        with
1>        [
1>            Encoding=rapidjson::UTF8<>
1>        ]
1>        C:\Program Files (x86)\MSVC9\VC\include\rapidjson/document.h(2282) : see declaration of 'rapidjson::GenericDocument<Encoding>::Parse'
1>        with
1>        [
1>            Encoding=rapidjson::UTF8<>
1>        ]
1>        C:\Program Files (x86)\MSVC9\VC\include\rapidjson/document.h(2289) : see declaration of 'rapidjson::GenericDocument<Encoding>::Parse'
1>        with
1>        [
1>            Encoding=rapidjson::UTF8<>
1>        ]
1>        C:\Program Files (x86)\MSVC9\VC\include\rapidjson/document.h(2289) : while compiling class template member function 'rapidjson::GenericDocument<Encoding> &rapidjson::GenericDocument<Encoding>::Parse(const char *)'
1>        with
1>        [
1>            Encoding=rapidjson::UTF8<>
1>        ]
1>        ..\rapidjson_tests.cpp(21) : see reference to class template instantiation 'rapidjson::GenericDocument<Encoding>' being compiled
1>        with
1>        [
1>            Encoding=rapidjson::UTF8<>
1>        ]
1>C:\Program Files (x86)\MSVC9\VC\include\rapidjson/document.h(82) : warning C4625: 'rapidjson::GenericMember<Encoding,Allocator>' : copy constructor could not be generated because a base class copy constructor is inaccessible
1>        with
1>        [
1>            Encoding=rapidjson::UTF8<>,
1>            Allocator=rapidjson::MemoryPoolAllocator<>
1>        ]
1>        C:\Program Files (x86)\MSVC9\VC\include\rapidjson/document.h(783) : see reference to class template instantiation 'rapidjson::GenericMember<Encoding,Allocator>' being compiled
1>        with
1>        [
1>            Encoding=rapidjson::UTF8<>,
1>            Allocator=rapidjson::MemoryPoolAllocator<>
1>        ]
1>        C:\Program Files (x86)\MSVC9\VC\include\rapidjson/document.h(769) : while compiling class template member function 'rapidjson::GenericValue<Encoding>::~GenericValue(void)'
1>        with
1>        [
1>            Encoding=rapidjson::UTF8<>
1>        ]
1>        C:\Program Files (x86)\MSVC9\VC\include\rapidjson/document.h(2074) : see reference to class template instantiation 'rapidjson::GenericValue<Encoding>' being compiled
1>        with
1>        [
1>            Encoding=rapidjson::UTF8<>
1>        ]
1>C:\Program Files (x86)\MSVC9\VC\include\rapidjson/document.h(2283) : warning C4347: behavior change: 'rapidjson::GenericDocument<Encoding> &rapidjson::GenericDocument<Encoding>::Parse<0,Encoding>(const char *)' is called instead of 'rapidjson::GenericDocument<Encoding> &rapidjson::GenericDocument<Encoding>::Parse(const char *)'
1>        with
1>        [
1>            Encoding=rapidjson::UTF8<>
1>        ]
1>        C:\Program Files (x86)\MSVC9\VC\include\rapidjson/document.h(2271) : see declaration of 'rapidjson::GenericDocument<Encoding>::Parse'
1>        with
1>        [
1>            Encoding=rapidjson::UTF8<>
1>        ]
1>        C:\Program Files (x86)\MSVC9\VC\include\rapidjson/document.h(2289) : see declaration of 'rapidjson::GenericDocument<Encoding>::Parse'
1>        with
1>        [
1>            Encoding=rapidjson::UTF8<>
1>        ]
1>        C:\Program Files (x86)\MSVC9\VC\include\rapidjson/document.h(2290) : see reference to function template instantiation 'rapidjson::GenericDocument<Encoding> &rapidjson::GenericDocument<Encoding>::Parse<0>(const char *)' being compiled
1>        with
1>        [
1>            Encoding=rapidjson::UTF8<>
1>        ]
1>        C:\Program Files (x86)\MSVC9\VC\include\rapidjson/document.h(2289) : while compiling class template member function 'rapidjson::GenericDocument<Encoding> &rapidjson::GenericDocument<Encoding>::Parse(const char *)'
1>        with
1>        [
1>            Encoding=rapidjson::UTF8<>
1>        ]
1>vcc - 1 error(s), 4 warning(s)
