### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by andrusha97** [miloyip/rapidjson#454]
Is there any roadmap for rapidjson? I'd like to know when to expect the next version and  what features it will contain.
(Actually I'd like to know when to expect a release with the comments feature which I contributed earlier)

**Comment by miloyip** [comment]
Currently I would like to make a release in coming November, which also merge the experimental JSON schema.

**Comment by dawnlucky** [comment]
Any plan?

**Comment by grisharav** [comment]
Also interested to know about this - the current documentation (http://rapidjson.org/) is not aligned with the release (1.0.2, https://github.com/miloyip/rapidjson/releases/tag/v1.0.2), for example the release is missing stream wrappers. I would prefer working with an official release of the library instead of some random changeset I chose.

**Comment by miloyip** [comment]
Yes, I have merged quite a lot of new features and improvements recently.
Now still trying to fix a few issues and then update the document and then will make a v1.1 release.
I won't adding new features in the mean time.
If you have time, please try the latest master and see if there is any issues.
Thank you.

**Comment by vasyan1337h4x0r** [comment]
How is it going?

**Comment by dawnlucky** [comment]
Coask?

**Comment by andrusha97** [comment]
v1.1.0 has just been released. Closing the issue.

**Comment by nicktrandafil** [comment]
There have been no releases for two years. I'm very interested in extended API for exposing schema validation error messages. When new release can be expected?
