### ISSUE TITLE
See the members that differ

### ISSUE THREAD

**Issue by alexandruirimiea** [miloyip/rapidjson#468]
Is there a possibility to compare two `rapidjson::Value`s and obtain a hint where the difference is?

E.g.: for the following two values, the different key is `key22`.

Document1:
```
{
    "key1": "value1"
    "key2": 
    {
        "key21": "value21"
        "key22": "value23"
    }
}
```

Document2:
```
{
    "key1": "value1"
    "key2": 
    {
        "key21": "value21"
        "key22": "value99"
    }
}
```
In order to detect if the two of them are different, I can use `operator==`, but I am not able to come up with an exact location of the difference, without an algorithm of less than O(n^2).

**Comment by miloyip** [comment]
O(n^2) runtime performance in `operator==` for object type is due to the fact that searching a key in members is O(n).

I think there are two basic methods to improve O(n^2) runtime performance.

1. Sort the members of two objects by keys in O(n log n), then you can compare the members between two objects linearly (e.g. pre-order traversals of both objects). This does not incur additional memory overhead. But the order of members are changed (in some application this may be undesired).
2. Use hash table to store members to obtain O(1) search for member. So that the comparison of objects will become O(n). But you need to create or copy the DOM with this data structure.

Another approach is to compute a hash code for every sub-trees. Then you can find out which sub-tree is different and then recursively find the different one. But caution needs to be taken for the possibility of hash collision.

**Comment by alexandruirimiea** [comment]
Yes, I remember you saying something about using the "commutative operator to combine the hashes of object members" in the branch _subtree_. I wish to understand this so I searched in the branch about the calculation, but I am not sure where to fund it. Can you give me a hint where to find the implementation?

**Comment by miloyip** [comment]
https://github.com/miloyip/rapidjson/blob/schema/include/rapidjson/schema.h#L185

This one uses XOR (an commutative operator) to combine hash codes of key-value pairs.
