### ISSUE TITLE
Warnings In Clang

### ISSUE THREAD

**Issue by capsocrates** [miloyip/rapidjson#473]
When compiling rapidjson from Clang 3.4.2 with all warning and error flags enabled, I get the warnings included in the attached buglisting.
[rapidjson-bugs.txt](https://github.com/miloyip/rapidjson/files/36934/rapidjson-bugs.txt)

**Comment by miloyip** [comment]
Can you provide the flags you have chosen?
Currently on clang we do `-Wall -Wextra -Werror -Wno-missing-field-initializers`.

**Comment by andrusha97** [comment]
Btw, if you don't want rapidjson to produce any warnings in your program, you can specify path to rapidjson header files with `-isystem` compiler option (instead of `-I`). It's especially designed for external libraries' includes.
If you use CMake, it provides `-isystem` support via `SYSTEM` option of `INCLUDE_DIRECTORIES` command.

**Comment by capsocrates** [comment]
I've been using -isystem to work around it.

I use the same flags (minus the missing-field one), but I also use -Weverything and -pedantic-errors

**Comment by miloyip** [comment]
I will try to fix `-Weverything`, but it will take some time.
