### ISSUE TITLE
Problem when addmember for existing document 

### ISSUE THREAD

**Issue by readandthink** [miloyip/rapidjson#475]
I meet a strange problem when modify a json object using rapidjson.

1. First I initialized a json object from string ("{}"), and  the json is an empty object (d = {})
2. then I add member for d["0"], now d = {"0": {"A": null}}
3. then I add another member for d["1"]
4. However when updating d["1"], d["0"] is also updated which is very strange 

Here is the complete code
```cpp
#include "rapidjson/document.h"
#include "rapidjson/writer.h"
#include "rapidjson/stringbuffer.h"
#include <iostream>
#include <string>

using namespace std;
using namespace rapidjson;

void output(Document& d)
{
    StringBuffer buffer;
    Writer<StringBuffer> writer(buffer);
    d.Accept(writer);
    cout << buffer.GetString() << endl;
}
int main()
{
    const char *json = "{}";
    int i=0;
    Document d; d.Parse(json);
    Document::AllocatorType& alloc = d.GetAllocator();

    //here we add two members in d, writing them separately into two blocks on purpose
    {
        Document d2; d2.Parse("{\"A\": null}");
        d.AddMember("0", d2, alloc);
        output(d);   // here is ok, output:  {"0":{"A":null}}
    }
    {
        Document d2; d2.Parse("{\"B\": null}");
        d.AddMember("1", d2, alloc);
        output(d);   //here is the problem, we get {"0":{"B":null},"1":{"B":null}}
    }
    return 0;
}
```
After compiling and running, we get the output
```
{"0":{"A":null}}
{"0":{"B":null},"1":{"B":null}}
```
d["0"] was modified after I add member for d["1"] which is beyond my expection.

However, if I wrote the two blocks like this
```cpp
    Document d2;
    d2.Parse("{\"A\": null}");
    d.AddMember("0", d2, alloc);
    output(d);  //{"0":{"A":null}}
    
    d2.Parse("{\"B\": null}");
    d.AddMember("1", d2, alloc);
    output(d);  //{"0":{"A:null},"1":{"B":null}}
```
then we got the expected output, 
```
{"0":{"A":null}}
{"0":{"A":null},"1":{"B":null}}
```
I've already known when AddMember, we actually run an "moving" syntax. after addMember, d2 will be knullType. so the next example works ok. However this still cannot explain the first one. why the second addMember will affect the previous key-value (i.e d["0"]) ?

Thank you for any suggestions.

**Comment by miloyip** [comment]
You cannot move document `d2` into another document `d`, and then destruct `d2` (at the end of the block). It is because during parsing, the values are allocated from `d2`. The allocator is destroyed when `d2` is destroyed.

You can deep copy `d2` into a value in `d1`, e.g.:
~~~cpp
Value v(d2, alloc); // deep copy
d.AddMember("0", v, alloc);
~~~

BTW, normally it is not a good idea to use parsing to initialize a simple value. For example, to make an empty object, simply:

~~~cpp
Document d;
d.SetObject();
~~~

or

~~~
Document d(kObjectType);
~~~

**Comment by readandthink** [comment]
Thank you, Milo. I read the code again and found the problem.
After existing from the first block, the allocator for d2 is destroyed when d2 is destroyed, and the corresponding pointer in d which points to the object in d2, is now a wild pointer.

And in the next block, we allocate memory for d2 again, by coincidence (since we didn't malloc in between the two block), the OS allocates the exactly same address for d2, after d2 parsing again, now d["0"] actually points to the new json object , and after calling addmember for d, both d["0"] and d["1"] points to the new json object allocated newly by d2. So we get the strange result.

And you're right, the better idea is to explicit declare an empty json object instead of parsing.

**Comment by tsingakbar** [comment]
> 
> 
> You cannot move document `d2` into another document `d`, and then destruct `d2` (at the end of the block). It is because during parsing, the values are allocated from `d2`. The allocator is destroyed when `d2` is destroyed.
> 
> You can deep copy `d2` into a value in `d1`, e.g.:
> 
> ```c++
> Value v(d2, alloc); // deep copy
> d.AddMember("0", v, alloc);
> ```

Have to say this design is somehow awkward. rapidjson is rapid because it avoids lots of copy, and now we have to deep copy to make basic operation work?
This should be documented in the manual: **Use AddMember to move a node from DocB to DocA, then you have to make sure DocB is not destroied while visiting DocA later, otherwise use deep copy**
But this really goes against most people's expectation: I moved shit from DocB to DocA, now DocA owned this shit, and we avoid copy, and everything is fast, but we have to keep DocB. This ownership is really confusing.
