### ISSUE TITLE
Add ability to parse json by parts

### ISSUE THREAD

**Issue by AlexeySagin** [miloyip/rapidjson#527]
The parser  enhancement  is required to parse json partially.
The following functionality of the lirary would be very helpful: the ability to send to the parser json request divided by separated parts as it is recieved from server/client/etc.
At the moment it has to wait until all the json parts are recieved and only then the complete json can be passed to the parser. It would be great if the parts can be passed to the parser separately.

**Comment by miloyip** [comment]
I think this is similar to [FAQ about Reader/Writer (SAX)](http://rapidjson.org/md_doc_faq.html):

> 2. Can I pause the parsing process and resume it later?

>   This is not directly supported in the current version due to performance consideration. However, if the execution environment supports multi-threading, user can parse a JSON in a separate thread, and pause it by blocking in the input stream.

**Comment by spl** [comment]
At one time, I wanted to be able to start parsing a string that contains a partial input (because the full input may not yet be available) and later continue parsing on more strings with remaining parts of the input. It sounds like the same thing that @AlexeySagin is requesting.

@miloyip I don't understand the question/answer in the FAQ and its connection to this issue. When I read “pause the parsing,” it sounds like an active choice I make to stop parsing, whereas I don't want to stop parsing but rather parsing should continue until it runs out of input, and I should be able to continue parsing with new input.

I believe this could be hacked together with RapidJSON as it is, but I never tried.

**Comment by miloyip** [comment]
To parse a JSON in multiple parts, it is like:

1. parse(partA);
2. do something else
3. parse(partB);
4. ...

Since currently the parser cannot resume its internal state (even iterative parser does not maintain internal states within single value), it will quite impossible to change the code to support this.

The workaround in FAQ:

Thread A
1. Lock buffer
2. FIll the buffer
3. Unlock buffer
4. Send signal that a buffer is available for parsing. 

Thread B
1. Start parsing
2. The stream wait until a signal
3. The stream fetch the data from buffer
4. When no data, wait for next signal.

Of course this can be done with double buffering so both threads can be run in parallel.
I am not sure if some coroutine solutions can help doing this concurrently. But these "hack" is platform-specific anyway.

Note that some parsers like YAJL can do parsing part by part. The tradeoff is the unavoidable performance penalty.

**Comment by spl** [comment]
@miloyip Thanks. That makes more sense.

**Comment by miloyip** [comment]
Maybe an example using pthread can demonstrate this.

**Comment by miloyip** [comment]
I created an example using C++11 thread. But I am not familiar with it.
Please help reviewing #556 .
