### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by jsvgoncalves** [miloyip/rapidjson#528]
Hey, 

I'm confused about the licensing for this project, could you please clarify which license applies?

Your README.md states:

> Copyright (C) 2015 THL A29 Limited, a Tencent company, and Milo Yip. All rights reserved.

And your code seems to have unclear licensing, which contradicts both itself and the one at README.md  i.e.:

```
// Copyright (C) 2015 THL A29 Limited, a Tencent company, and Milo Yip. All rights reserved.
//
// Licensed under the MIT License (the "License"); you may not use this file except
```

**Comment by miloyip** [comment]
MIT license.
The readme just states the copyright owner. It does not conflict with how the project's licensing term.

**Comment by jsvgoncalves** [comment]
Ok thanks! :)

**Comment by ssb22** [comment]
The confusion might arise from the words "All rights reserved", which [should not be used with the MIT license](https://opensource.stackexchange.com/a/4403/20672) (some people think they have to use those words because of the BSD license and the old Buenos Aires copyright convention, which was made obsolete by the Berne copyright convention).
