### ISSUE TITLE
Slowing down significantly

### ISSUE THREAD

**Issue by darkjacky** [miloyip/rapidjson#592]
I have searched the issues but I could not find something similar.

I have the following code:
```
rapidjson::Document d;
d.Parse(json);

if (!d.HasParseError()) {
	char buf[10];
	long long count;
	int i = 1;
	auto end = d.MemberEnd();
	while (true) {
		auto t1 = std::chrono::steady_clock::now();
		sprintf(buf, "%u", i++);
		auto tab = d.FindMember(buf);
		if ((tab != end)) {
			d.RemoveMember(tab);
		}
		else break;
		count += (std::chrono::steady_clock::now() - t1).count();
		if (i % 10000 == 2) {
			std::cout << buf << " " << d.MemberCount() << " " << count << std::endl;
			count = 0;
		}
	}
}
```
const char * json is a 83MB valid JSON. Containing 836460 members.
In the begin parsing it is fast. But then it start slowing down. Results below in nanoseconds.
After the 50% mark it speeds up again.

```
cur / left / time
1 836459 5852
10001 826459 198661984
20001 816459 593957406
30001 806459 984389065
40001 796459 1382457778
50001 786459 1783725955
60001 776459 2174998134
70001 766459 2569019356
80001 756459 2980782011
90001 746459 3384107829
100001 736459 3780264800
...
180001 656459 10418938177
...
420001 416459 24869877902 // almost 25 seconds
...
670001 166459 10064007622
...
830001 6459 678674262
```

What am I doing wrong?

**Comment by andrusha97** [comment]
It might be related to this issue https://github.com/miloyip/rapidjson/issues/570.
RemoveMember() by iterator takes constant time, so you mostly measure performance of FindMember().
What is the order of members in your json? It may be something like this: 1, 10, 11, 12, ..., 2, 20, 21, 22, ..., 3, 30, 31, 32, ...
In this case search for 2 will take longer then search for 1 and search for 3 longer than search for 2, because to find an element you need to traverse all elements preceding it.

By the way, RemoveMember() probably invalidates the end iterator, so you cannot reuse it between iterations of the loop. Also you better not call std::chrono::steady_clock::now() on every iteration, because it's pretty slow (though not enough to affect results in your case).

**Comment by darkjacky** [comment]
The order is 1,2,3,4 etc.
And if I remove the RemoveMember() it will add about 50% time to the entire process.

```
1 836460 7608
10001 836460 276149539
20001 836460 683212359
30001 836460 1260120549
40001 836460 1837749654
50001 836460 2415050769
60001 836460 3024365725
70001 836460 3622579474
80001 836460 4144593548
90001 836460 4709375641
100001 836460 5337907597
```

It is just a test I setup because I got slow results.

**Comment by andrusha97** [comment]
> And if I remove the RemoveMember() it will add about 50% time to the entire process.
Yep. Because you remove elements, at some point FindMember() starts take less and less time. If you do not remove them, every iteration takes more time then the previous one.
To be precise, RemoveMember() takes the last element and places it instead of the removed one. So, for the first half of the members,  even though you remove them, FindMember() still need to iterate through N items to find the one with key N. Then "After the 50% mark it speeds up again."

**Comment by darkjacky** [comment]
I see that is interesting. So a way around that would be to perhaps get first, get last, get first, get last etc? I will test that anyway.

**Comment by miloyip** [comment]
RapidJSON provides high-performance JSON parsing and generation. However, to make it fast for that, query via `FindMember()` is O(n). This is a tradeoff. To make query faster, you should convert the data to some faster data structure for storing key-values, such as `unordered_map`. But that will have downside of not preserving the order of keys.

**Comment by darkjacky** [comment]
Ok so I tried using unordered map. That however crashed due to bad JSON. Then when I switched back to mapped JSON with my new method I noticed it was much quicker.

I am now using the rapidjson::Value::ConstMemberIterator and just loop that way. I create a simple std::deque with the same size as my JSON array. I then get the member name and convert that into an int then push it into the deque.
The parse time went from multiple minutes to just 3.7 seconds total. (Before I optimized it.)

Thank you for your help. It really did help.
