### ISSUE TITLE
Performance problem with wofstream

### ISSUE THREAD

**Issue by ArphonePei** [miloyip/rapidjson#623]
I have a buffer (which is a StringBuffer) containing about 100000 objects, when I try to write it to a file, I notice a performance difference between ofstream and wofstream. The code is quite straight forward:

`wofstream fo(_T("d:/out_rapidjson.json"));`
`fo << buffer.GetString();`
`fo.close();`

When I use ofstream it takes about 5 seconds while in wofstream it takes about 1 minute, so I am wondering if the is a problem of wofstream or StringBuffer.

compiler: msvc v100

**Comment by miloyip** [comment]
`StringBuffer::GetString()` returns a `const char*` pointer in amortized O(1) time.

It is a problem of `wofstream` which needs to do [narrow-to-wide conversion](http://en.cppreference.com/w/cpp/io/basic_ios/widen).

For performance consideration, you can write UTF-8 JSON into a binary file using `FILE*`, instead of using `iostream`.

**Comment by ArphonePei** [comment]
Thanks for the explaination.
