### ISSUE TITLE
Document.IsObject() is wrong (not talking about bad json formatting)

### ISSUE THREAD

**Issue by Undume** [miloyip/rapidjson#840]
The method document.isObject() is returning false when it is actually true.

Flag 3 means object no? When it does the conditional, this is returning false.

![screen shot 2017-02-02 at 1 30 47 pm](https://cloud.githubusercontent.com/assets/5592771/22549485/dc40981e-e94b-11e6-9450-652d930390e7.png)

The include is from the external libraries of cocos2d-x 3.14.1
#include "json/document.h"

```
string rawJson="{\"parent\":{ \"children1\": { \"name\": \"lovecraft\",      \"age\": \"100\" } , \"children2\": {      \"name\": \"poe\",      \"age\": \"102\" },\"children3\": {      \"name\": \"wilde\",      \"age\": \"155\" }}}";
    Document document;
    document.Parse<0>(rawJson.c_str());
    
    CCLOG("flag %d",document.IsObject()); //return 0
```

and a more friendly view of the json:

"{ 
	\”parent\”:
	{
		\”children1\”: {      \”name\”: \”lovecraft\”,      \”age\”: \”100\” },  
		\”children2\”: {      \”name\”: \”poe\”,      \”age\”: \”102\” },
		\”children3\”: {      \”name\”: \”wilde\”,      \”age\”: \”155\” }
	}
}"

Using the same code with the external json libraries from cocos2d-x 3.10 it works.

**Comment by miloyip** [comment]
I think it may be due that, inside a same application, there are two versions of RapidJSON and then linker may get confused. Since different versions of RapidJSON may have different internal data layout, it may create unexpected behavior.

Since Cocos2DX uses RapidJSON, if you want another version of RapidJSON, you can define `RAPIDJSON_NAMESPACE` before including rapidjson headers in your code.

**Comment by Undume** [comment]
True, we had two different rapidjson libraries in the project. I take out the old one and now is working fine! Thanks!
