### ISSUE TITLE
Warning: Not enough actual parameters for macro 'max'

### ISSUE THREAD

**Issue by mtebele** [miloyip/rapidjson#984]
Hi! I'm getting the following warnings when compiling my project:

`1>c:\users\matt-pc\desktop\uba\7542-sonic\sonic\libs\rapidjson\document.h(958): warning C4003: not enough actual parameters for macro 'max'`

`1>c:\users\matt-pc\desktop\uba\7542-sonic\sonic\libs\rapidjson\document.h(964): warning C4003: not enough actual parameters for macro 'min'`

`1>c:\users\matt-pc\desktop\uba\7542-sonic\sonic\libs\rapidjson\document.h(965): warning C4003: not enough actual parameters for macro 'max'`

`1>c:\users\matt-pc\desktop\uba\7542-sonic\sonic\libs\rapidjson\document.h(982): warning C4003: not enough actual parameters for macro 'max'`

`1>c:\users\matt-pc\desktop\uba\7542-sonic\sonic\libs\rapidjson\document.h(983): warning C4003: not enough actual parameters for macro 'max'`

It happens with the latest release v1.1.0.

**Comment by miloyip** [comment]
It uses the C++ standard library 
`std::numeric_limits<uint64_t>::max()` and so on.
I think your project may include a header which defines a macro `max(a, b)`. 

If it is due to `windef.h`, see [stackoverflow](https://stackoverflow.com/questions/11544073/how-do-i-deal-with-the-max-macro-in-windows-h-colliding-with-max-in-std).

**Comment by mtebele** [comment]
Thanks!

**Comment by mladenmilev** [comment]
I get the same error and my question is how to resolve it if the rest of the code uses the `windef.h`  min(a,b,)` and `max(a,b)`.
