### ISSUE TITLE
Float equal failed

### ISSUE THREAD

**Issue by zammbi** [miloyip/rapidjson#991]
I have a unit test failing in my code and I've narrowed it down to a float issue in rapidjson. 

```
	Document doc(kObjectType);
	doc.AddMember("value1", 12.272727012634277, doc.GetAllocator());
 
	Document doc2;
	doc2.Parse("{\"value2\":12.272727012634277}");

	REQUIRE(doc == doc2);
```

Printing out value 1 gives "12.272727012634278" and printing out value 2 gives "12.272727012634276". They should be the same. 

PS: it would be great if rapidjson worked a little more nicely with the testing library catch (https://github.com/philsquared/Catch). E.g allow Catch to print the json on failed tests (https://github.com/philsquared/Catch/blob/master/docs/tostring.md).

**Comment by pah** [comment]
By default, RapidJSON is potentially slightly inaccurate wrt. parsing floating point values, see [here](https://github.com/miloyip/rapidjson/blob/master/doc/internals.md#parsing-to-double-parsingdouble) (the generated documentation at http://rapidjson.org/md_doc_internals.html#ParsingDouble seems to be broken here).

In order to achieve full precision, you need to use the `kParseFullPrecisionFlag` for parsing, see http://rapidjson.org/md_doc_dom.html#Parsing. 

PS: Adding a default `operator<<(std::ostream&, ...)` for RapidJSON values does not sound reasonable to me. It's pretty straight forward to implement your own string support for Catch:
````cpp
namespace Catch {
    template<> struct StringMaker<rapidjson::Value> {
        static std::string convert( rapidjson::Document const& value ) {
            rapidjson::StringBuffer buf;
            rapidjson::Writer<rapidjson::StringBuffer> writer(buf);
            return std::string( buf.GetString(), buf.GetLength() );
        }
    };
    template<> struct StringMaker<rapidjson::Document> {
        static std::string convert( rapidjson::Document const& value ) {
            return StringMaker<rapidjson::Value>(value);
        }
    };
} // namespace Catch
````

**Comment by zammbi** [comment]
Thanks @pah both worked for me.
